import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import dayjs from "dayjs";

vi.mock("../src/lib/config.js", () => ({
  loadConfig: vi.fn(),
  resolveLogsDir: vi.fn((dir: string) => dir),
}));

vi.mock("../src/lib/storage.js", () => ({
  readLog: vi.fn(),
}));

import { loadConfig } from "../src/lib/config.js";
import { readLog } from "../src/lib/storage.js";
import { runExport, formatLogAsMarkdown } from "../src/commands/export.js";
import type { DevLog } from "../src/lib/types.js";

const mockLoadConfig = vi.mocked(loadConfig);
const mockReadLog = vi.mocked(readLog);

const TEST_LOG: DevLog = {
  date: "2026-03-20",
  type: "daily",
  raw: {
    date: "2026-03-20",
    commits: ["fix: auth bug", "refactor: split middleware"],
    filesChanged: ["auth.ts", "middleware.ts"],
    insertions: 42,
    deletions: 11,
  },
  summary:
    "• Resolved race condition in auth module\n• Refactored middleware into composable functions",
  generatedAt: "2026-03-20T14:32:00Z",
};

describe("formatLogAsMarkdown", () => {
  it("should include the date header", () => {
    const md = formatLogAsMarkdown(TEST_LOG);
    expect(md).toContain("## Dev Log — March 20, 2026");
  });

  it("should include the summary section", () => {
    const md = formatLogAsMarkdown(TEST_LOG);
    expect(md).toContain("### Summary");
    expect(md).toContain("Resolved race condition");
    expect(md).toContain("Refactored middleware");
  });

  it("should include git stats", () => {
    const md = formatLogAsMarkdown(TEST_LOG);
    expect(md).toContain("### Git Stats");
    expect(md).toContain("auth.ts");
    expect(md).toContain("middleware.ts");
    expect(md).toContain("+42");
    expect(md).toContain("-11");
  });

  it("should include the footer", () => {
    const md = formatLogAsMarkdown(TEST_LOG);
    expect(md).toContain("Generated by devlog");
  });
});

describe("runExport", () => {
  let tempDir: string;
  let originalCwd: string;

  beforeEach(async () => {
    vi.clearAllMocks();
    process.exitCode = undefined;
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "devlog-export-test-"));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  function setupConfig() {
    mockLoadConfig.mockResolvedValue({
      apiKey: "sk-ant-test",
      defaultTone: "daily",
      logsDir: "/tmp/devlog-test/logs",
    });
  }

  it("should default to today's date when no argument given", async () => {
    setupConfig();
    mockReadLog.mockResolvedValue(TEST_LOG);
    const today = dayjs().format("YYYY-MM-DD");

    await runExport();

    expect(mockReadLog).toHaveBeenCalledWith(today, expect.any(String));
  });

  it("should export a specific date's log when date given", async () => {
    setupConfig();
    mockReadLog.mockResolvedValue(TEST_LOG);

    await runExport("2026-03-20");

    expect(mockReadLog).toHaveBeenCalledWith("2026-03-20", expect.any(String));
  });

  it("should write markdown file to current directory", async () => {
    setupConfig();
    mockReadLog.mockResolvedValue(TEST_LOG);

    await runExport("2026-03-20");

    const outputPath = path.join(tempDir, "devlog-export-2026-03-20.md");
    const content = await fs.readFile(outputPath, "utf-8");
    expect(content).toContain("## Dev Log");
    expect(content).toContain("Resolved race condition");
  });

  it("should error when no saved log exists for that date", async () => {
    setupConfig();
    mockReadLog.mockResolvedValue(null);

    await runExport("2026-03-20");

    expect(process.exitCode).toBe(1);
  });

  it("should error when no config exists", async () => {
    mockLoadConfig.mockResolvedValue(null);

    await runExport();

    expect(process.exitCode).toBe(1);
    expect(mockReadLog).not.toHaveBeenCalled();
  });

  it("should reject invalid date format", async () => {
    setupConfig();

    await runExport("not-a-date");

    expect(process.exitCode).toBe(1);
    expect(mockReadLog).not.toHaveBeenCalled();
  });
});
