import * as fs from "node:fs/promises";
import * as path from "node:path";
import { loadConfig, resolveLogsDir } from "../lib/config.js";
import { readLog } from "../lib/storage.js";
import { todayDate, formatDisplayDate, parseDate } from "../utils/date.js";
import { printError } from "../utils/format.js";
import type { DevLog } from "../lib/types.js";

const DATE_REGEX = /^\d{4}-\d{2}-\d{2}$/;

/**
 * Convert a DevLog into a markdown string.
 */
export function formatLogAsMarkdown(log: DevLog): string {
  const displayDate = formatDisplayDate(log.date);

  const summaryLines = log.summary
    .split("\n")
    .map((line) => {
      const trimmed = line.trim();
      if (!trimmed) return "";
      // Normalize bullet points to markdown list items
      return trimmed.startsWith("•")
        ? `- ${trimmed.slice(1).trim()}`
        : `- ${trimmed}`;
    })
    .filter((line) => line.length > 0);

  const lines = [
    `## Dev Log — ${displayDate}`,
    "",
    "### Summary",
    ...summaryLines,
    "",
    "### Git Stats",
    `- Files changed: ${log.raw.filesChanged.join(", ") || "none"}`,
    `- Lines: +${log.raw.insertions} -${log.raw.deletions}`,
    "",
    "---",
    "Generated by devlog",
    "",
  ];

  return lines.join("\n");
}

export async function runExport(dateInput?: string): Promise<string> {
  const config = await loadConfig();
  if (!config) {
    printError(
      'No config found. Run "devlog init" first to set up your API key.',
    );
    process.exitCode = 1;
    return "";
  }

  let date: string;
  if (dateInput) {
    if (!DATE_REGEX.test(dateInput)) {
      printError("Invalid date format. Use YYYY-MM-DD");
      process.exitCode = 1;
      return "";
    }
    const parsed = parseDate(dateInput);
    if (!parsed) {
      printError("Invalid date format. Use YYYY-MM-DD");
      process.exitCode = 1;
      return "";
    }
    date = parsed;
  } else {
    date = todayDate();
  }

  const logsDir = resolveLogsDir(config.logsDir);
  const log = await readLog(date, logsDir);

  if (!log) {
    printError(
      `No log found for ${date}. Run "devlog today" first.`,
    );
    process.exitCode = 1;
    return "";
  }

  const markdown = formatLogAsMarkdown(log);
  const filename = `devlog-export-${date}.md`;
  const outputPath = path.join(process.cwd(), filename);

  try {
    await fs.writeFile(outputPath, markdown, "utf-8");
    const msg = `Exported → ${outputPath}`;
    console.log(`✓ ${msg}`);
    return msg;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    printError(`Failed to write export: ${message}`);
    process.exitCode = 1;
    return "";
  }
}
